### ISSUE TITLE
xml syntax/indenting isn't loaded

### ISSUE THREAD

**Issue by davetron5000** [nelstrom/vim-pml#4]
Despite this line being in `ftplugin/pml.vim`:

```
runtime! syntax/xml.vim
```

I get no syntax highlighting.  If I add this to my `.vimrc`:

```
au BufEnter *.pml runtime syntax/xml.vim
```

it works.

Similarly, I must add

```
au BufEnter *.pml runtime indent/xml.vim
```

to get indenting to work.

I setup my vim from scratch using pathogen, with these plugins:
- Command-T/
- scala-vim-support/
- snipmate.vim/
- textile.vim/
- vim-bufexplorer/
- vim-cucumber/
- vim-git/
- vim-haml/
- vim-markdown/
- vim-matchit/
- vim-pml/
- vim-ruby/
- vim-taglist/
- vim-xml-autons/

**Comment by nelstrom** [comment]
Thanks for reporting this. I've been able to reproduce the behaviour that you describe sporadically. I'll look further into it.

**Comment by nelstrom** [comment]
My apologies for neglecting this. There are actually two separate issues here: the syntax is not being loaded, and the indentation is not being loaded.

Although the commit message suggests that I was actually tackling another issue at the time, I think that [this commit](https://github.com/nelstrom/vim-pml/commit/68f242ec4627d2759f70f669a39fdc65ed0c92ff) should have fixed the issue with syntax loading.

[This patch](https://github.com/nelstrom/vim-pml/pull/7) from @tswicegood should fix the remaining issue with the xml indentation. It turns out that the reason I wasn't able to reproduce the issue was because [another plugin](https://github.com/tpope/vim-ragtag) was enabling XML indentation for me. When I disabled the ragtag plugin, I experienced the same issue.

@davetron5000: could you try updating to the latest version of pml.vim and removing these lines from your vimrc:

```
au BufEnter *.pml runtime syntax/xml.vim
au BufEnter *.pml runtime indent/xml.vim
```

If this issue has been resolved, you shouldn't need them.
